spring.application.name=physioApp
# MySQL Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/PhysioApp
spring.datasource.username=Physio_app_User
#spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# application.properties
spring.jackson.mapper.accept-case-insensitive-enums=true

logging.level.springframework.beans=debug
logging.level.org.springframework.web=debug
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=trace

management.endpoints.web.exposure.include=health,info,metrics,mappings,beans
spring.web.error.include-stacktrace=never

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#logging.level.com.netflix.discovery=DEBUG